# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
# chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
dataset_mixer:
#  deepvk/deepvk-sft-ru: 1.0
#  deepvk/ultrachat-commandr-ru: 1.0
#  deepvk/openorca-ru: 1.0
#  deepvk/glaive-code-assistant-v3: 1
#  deepvk/orca-math-word-problems-200k: 1
#  deepvk/camel_physics: 1
#  deepvk/camel_math: 1
  deepvk/camel_chemistry: 1
#  deepvk/camel_biology: 1
#  deepvk/ultrafeedback_binarized: 1
#  deepvk/foundation: 1
#  deepvk/ultrachat_200k: 1
dataset_splits:
  - train
  - test
preprocessing_num_workers: 48

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: deepvk-3b-sft
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 10
output_dir: /nfs/ksemin/zephyr/checkpoints/llama-3-8b-sft-new-ds-eng-ultra-debug/
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 100
seed: 42
warmup_ratio: 0.1