# Model arguments
model_name_or_path: deepvk/Socrates-8b-sft-v4
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
#  HuggingFaceH4/ultrafeedback_binarized: 1.0
#  deepvk/commandr-gpt3-pref: 1.0
  deepvk/ultrachat-prefs-gpt4o-vs-socrates-sft-v4: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-dpo-full
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 3
optim: adamw_torch
output_dir: /nfs/ksemin/zephyr/checkpoints/Socrates-8b-dpo-v4-3ep
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 100
seed: 42
warmup_ratio: 0.1